version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  commit-message:
    prefix: 'chore(deps): '
  open-pull-requests-limit: 1
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  commit-message:
    prefix: 'chore(deps): '
  open-pull-requests-limit: 1
