name: Release

on:
  push:
    tags:
      - 'v*'

env:
  POETRY_CACHE_DIR: ".cache/poetry"
  PIP_CACHE_DIR: ".cache/pip"

jobs:
    publish:
      name: "Publish package"
      runs-on: ubuntu-latest
      if: github.event.base_ref == 'refs/heads/master'

      steps:
        - name: Checkout code
          uses: actions/checkout@v2.3.3

        - name: "Get python version"
          uses: outcome-co/action-read-toml@v1.9.2
          id: python_version
          with:
            path: pyproject.toml
            key: tool.poetry.dependencies.python

        - name: "Set up python ${{ steps.python_version.outputs.tool_poetry_dependencies_python }}"
          uses: actions/setup-python@v2.1.3
          with:
            python-version: ${{ steps.python_version.outputs.tool_poetry_dependencies_python }}

        - name: Configure pip cache
          uses: actions/cache@v2
          with:
            path: ${{ env.PIP_CACHE_DIR }}
            # Pip is only used to install poetry, and the poetry version 
            # is stored in pyproject.toml
            key: pip-${{ hashFiles('**/pyproject.toml') }}

        - name: Configure poetry cache
          uses: actions/cache@v2
          with:
            path: ${{ env.POETRY_CACHE_DIR }}
            # All of the dependencies are stored in pyproject.toml
            key: poetry-${{ hashFiles('**/poetry.lock') }}

        - name: "Install dev dependencies"
          run: make dev-setup

        - name: "Publish package"
          run: make publish
          env:
            POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_REGISTRY_TOKEN }}
